# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: SERVER distribute

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/dev/my-weather-app
            sudo rm yarn.lock
            sudo git pull
            sudo npm install
            sudo npm run build
            sudo pm2 restart 0 --update-env
